version: "3.8"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src # ローカルをコンテナ内にマウント
    command: sh -c "cd app && PORT=3001 yarn start" # 3001ポートで yarn start
    ports:
      - "3001:3001"
    stdin_open: true
